Env concept
avenga/couper-vscode pull request #92
Opened 2022-06-10 10:31 UTC by alex-schneider

2022-06-27 07:42 UTC, afflerbach commented on src/schema.js
> +		parents: ['environment', 'server'],
Unfortunately, this renders the completion almost useless. With `environment` as every blocks/attributes parent, the completion always suggests *all* blocks/attributes as possible children for `environment`:

![broken_completion](https://user-images.githubusercontent.com/1311513/175886491-22c0acf7-280e-4281-912e-64841436832d.gif)
ironment`.

2022-06-27 07:42 UTC, malud requested changes
Since all blocks are childs of `environment` the will be suggested on invalid places.

```hcl
environment "…" {
    server {
        environment "…" {
            endpoint "/" {
                proxy {
                    environment "…" {
                        oauth2 {
                            // invalid
                        }
                        access_control = [""] // invalid
                    }
                }
            }
        }
    }
}
```

2022-06-27 07:47 UTC, afflerbach requested changes
I guess we have to handle `environment` specially without adding it to the general schema.

2022-08-11 13:18 UTC, johakoch approved these changes
Approved on behalf of alex-schneider

2022-08-11 13:34 UTC, malud approved these changes

2022-08-11 13:37 UTC, merged